### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by HeynSekk** [HeynSekk/save-lives#3]
Welcoming HacktoberFest contributions

**Comment by sayaPintar** [comment]
can i contribute with code CSharp?

**Comment by HeynSekk** [comment]
Which feature would you like to contribute?
Currently, Save Lives, this app's working fine using Flutter framework that use Dart Language as primary language 👍. Thanks for asking.

**Comment by Amitbhave** [comment]
@HeynSekk can you add issues that need to be fixed/ feature roadmap for which I can contribute to?

**Comment by HeynSekk** [comment]
Okay bro. I will add some issues and roadmap tomorrow. Thanks 😊 for your will to contribute this project. After adding, I will mention you.
